docs(contrib): Fix steps to work on duplicate entries
The instructions previously instructed the contributor
to run `SNAPSHOTS=overwrite cargo test` which will however
fail when the added entry is duplicate with:

    thread 'codegen' panicked at 'Duplicate present: ...'

Duplicates have to be removed by firstly running the verify
test with SNAPSHOTS=overwrite before you should try running
the code generation.

These were actually the steps before they were
changed in 7eb88739501dcce6eaca5089910a94151a91f96b
(which appears to have been an oversight).